class UserAlreadyExistsError(Exception):
    pass

class UserDoesntExistError(Exception):
    pass